### ISSUE TITLE
This operation is not permitted on KinesisStreamAsSource delivery stream type.

### ISSUE THREAD

**Issue by erick1979** [awslabs/lambda-streams-to-firehose#60]
My putRecordBatchParams:
`{
    "DeliveryStreamName": "Delivery-TTL-Teste",
    "Records": [
        {
            "Data": {
                "type": "Buffer",
                "data": [
                    123,
                    34,
                    75,
                    101,
                    121,
                    115,
                    34,
                    58,
                    123,
                    34,
                    115,
                    101,
                    115,
                    115,
                    105,
                    111,
                    110,
                    105,
                    100,
                    34,
                    58,
                    123,
                    34,
                    83,
                    34,
                    58,
                    34,
                    98,
                    56,
                    99,
                    52,
                    57,
                    97,
                    99,
                    56,
                    45,
                    97,
                    49,
                    56,
                    49,
                    45,
                    52,
                    100,
                    53,
                    98,
                    45,
                    57,
                    49,
                    98,
                    102,
                    45,
                    101,
                    101,
                    100,
                    97,
                    52,
                    100,
                    100,
                    99,
                    98,
                    98,
                    51,
                    50,
                    34,
                    125,
                    125,
                    44,
                    34,
                    79,
                    108,
                    100,
                    73,
                    109,
                    97,
                    103,
                    101,
                    34,
                    58,
                    123,
                    34,
                    67,
                    114,
                    101,
                    97,
                    116,
                    105,
                    111,
                    110,
                    84,
                    105,
                    109,
                    101,
                    34,
                    58,
                    123,
                    34,
                    78,
                    34,
                    58,
                    34,
                    49,
                    53,
                    52,
                    55,
                    54,
                    54,
                    51,
                    54,
                    49,
                    55,
                    34,
                    125,
                    44,
                    34,
                    83,
                    101,
                    115,
                    115,
                    105,
                    111,
                    110,
                    68,
                    97,
                    116,
                    97,
                    34,
                    58,
                    123,
                    34,
                    77,
                    34,
                    58,
                    123,
                    34,
                    82,
                    101,
                    116,
                    97,
                    105,
                    108,
                    101,
                    114,
                    34,
                    58,
                    123,
                    34,
                    83,
                    34,
                    58,
                    34,
                    115,
                    104,
                    111,
                    112,
                    114,
                    105,
                    116,
                    101,
                    34,
                    125,
                    44,
                    34,
                    84,
                    105,
                    109,
                    101,
                    79,
                    102,
                    84,
                    114,
                    97,
                    110,
                    115,
                    97,
                    99,
                    116,
                    105,
                    111,
                    110,
                    34,
                    58,
                    123,
                    34,
                    78,
                    34,
                    58,
                    34,
                    49,
                    53,
                    52,
                    55,
                    54,
                    54,
                    51,
                    54,
                    49,
                    55,
                    34,
                    125,
                    44,
                    34,
                    65,
                    109,
                    111,
                    117,
                    110,
                    116,
                    34,
                    58,
                    123,
                    34,
                    78,
                    34,
                    58,
                    34,
                    55,
                    56,
                    57,
                    56,
                    34,
                    125,
                    44,
                    34,
                    78,
                    97,
                    109,
                    101,
                    34,
                    58,
                    123,
                    34,
                    83,
                    34,
                    58,
                    34,
                    119,
                    105,
                    108,
                    108,
                    105,
                    97,
                    109,
                    34,
                    125,
                    125,
                    125,
                    44,
                    34,
                    115,
                    101,
                    115,
                    115,
                    105,
                    111,
                    110,
                    105,
                    100,
                    34,
                    58,
                    123,
                    34,
                    83,
                    34,
                    58,
                    34,
                    98,
                    56,
                    99,
                    52,
                    57,
                    97,
                    99,
                    56,
                    45,
                    97,
                    49,
                    56,
                    49,
                    45,
                    52,
                    100,
                    53,
                    98,
                    45,
                    57,
                    49,
                    98,
                    102,
                    45,
                    101,
                    101,
                    100,
                    97,
                    52,
                    100,
                    100,
                    99,
                    98,
                    98,
                    51,
                    50,
                    34,
                    125,
                    44,
                    34,
                    69,
                    120,
                    112,
                    105,
                    114,
                    97,
                    116,
                    105,
                    111,
                    110,
                    84,
                    105,
                    109,
                    101,
                    34,
                    58,
                    123,
                    34,
                    78,
                    34,
                    58,
                    34,
                    49,
                    53,
                    52,
                    55,
                    54,
                    54,
                    55,
                    50,
                    49,
                    55,
                    34,
                    125,
                    125,
                    44,
                    34,
                    83,
                    101,
                    113,
                    117,
                    101,
                    110,
                    99,
                    101,
                    78,
                    117,
                    109,
                    98,
                    101,
                    114,
                    34,
                    58,
                    34,
                    49,
                    57,
                    48,
                    50,
                    56,
                    53,
                    49,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    48,
                    51,
                    55,
                    57,
                    57,
                    49,
                    50,
                    52,
                    55,
                    49,
                    34,
                    44,
                    34,
                    83,
                    105,
                    122,
                    101,
                    66,
                    121,
                    116,
                    101,
                    115,
                    34,
                    58,
                    50,
                    48,
                    53,
                    44,
                    34,
                    65,
                    112,
                    112,
                    114,
                    111,
                    120,
                    105,
                    109,
                    97,
                    116,
                    101,
                    67,
                    114,
                    101,
                    97,
                    116,
                    105,
                    111,
                    110,
                    68,
                    97,
                    116,
                    101,
                    84,
                    105,
                    109,
                    101,
                    34,
                    58,
                    49,
                    53,
                    52,
                    55,
                    54,
                    54,
                    55,
                    55,
                    55,
                    53,
                    44,
                    34,
                    101,
                    118,
                    101,
                    110,
                    116,
                    78,
                    97,
                    109,
                    101,
                    34,
                    58,
                    34,
                    82,
                    69,
                    77,
                    79,
                    86,
                    69,
                    34,
                    44,
                    34,
                    117,
                    115,
                    101,
                    114,
                    73,
                    100,
                    101,
                    110,
                    116,
                    105,
                    116,
                    121,
                    34,
                    58,
                    123,
                    34,
                    112,
                    114,
                    105,
                    110,
                    99,
                    105,
                    112,
                    97,
                    108,
                    73,
                    100,
                    34,
                    58,
                    34,
                    100,
                    121,
                    110,
                    97,
                    109,
                    111,
                    100,
                    98,
                    46,
                    97,
                    109,
                    97,
                    122,
                    111,
                    110,
                    97,
                    119,
                    115,
                    46,
                    99,
                    111,
                    109,
                    34,
                    44,
                    34,
                    116,
                    121,
                    112,
                    101,
                    34,
                    58,
                    34,
                    83,
                    101,
                    114,
                    118,
                    105,
                    99,
                    101,
                    34,
                    125,
                    125,
                    10
                ]
            }
        }
   ]
}`

Erro:
2019-01-18T02:07:20.961Z	fae1d2a0-12e2-4bfe-9864-1bb7a5da5cf3	{ InvalidArgumentException: This operation is not permitted on KinesisStreamAsSource delivery stream type.
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'This operation is not permitted on KinesisStreamAsSource delivery stream type.',
code: 'InvalidArgumentException',
time: 2019-01-18T02:07:20.961Z,
requestId: 'e1d8a349-23f4-bc6d-b563-94519964e77c',
statusCode: 400,
retryable: false,
retryDelay: 71.66140146807749 }

Which is my problem? Any Idea?

**Comment by erick1979** [comment]
My problem has been solved. But generate files with ERROR, but not show error.

**Comment by Sagargupta483** [comment]
Can you please let us know how did you solve this issue?

**Comment by erick1979** [comment]
Hi,

I do this:
![image](https://user-images.githubusercontent.com/46802822/56042698-0a976800-5d12-11e9-905a-6bd010312835.png)

and the problem was resolved when I check disabled [Transform source records with AWS Lambda] in Kinesis.

![image](https://user-images.githubusercontent.com/46802822/56042591-d1f78e80-5d11-11e9-9890-65313f5c798e.png)

I guess have error on tutorial!
